- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Grafana directory
  file:
    path: "{{ app_dir }}/grafana"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: "{{ compose_src }}"
    dest: "{{ app_dir }}/grafana/docker-compose.yml"
    mode: '0644'

- name: Create Grafana directory
  file:
    path: "{{ app_dir }}/grafana"
    state: directory
    mode: '0755'

- name: Copy Grafana provisioning
  copy:
    src: provisioning/
    dest: "{{ app_dir }}/grafana/provisioning"
    mode: '0644'

- name: Stop services with docker-compose
  command: docker compose down
  args:
    chdir: "{{ app_dir }}/grafana"

- name: Start services with docker-compose
  command: docker compose up -d
  args:
    chdir: "{{ app_dir }}/grafana"
