- name: Create application directory
  file:
    path: "{{ APP_DIR }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Prometheus directory
  file:
    path: "{{ APP_DIR }}/prometheus"
    state: directory
    mode: '0755'


- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ APP_DIR }}/prometheus/prometheus.yml"
    mode: '0644'

- name: Copy docker-compose.yml
  template:
    src: "{{ COMPOSE_SRC }}"
    dest: "{{ APP_DIR }}/prometheus/docker-compose.yml"
    mode: '0644'

- name: Stop services with docker-compose
  command: docker compose down
  args:
    chdir: "{{ APP_DIR }}/prometheus"

- name: Start services with docker-compose
  command: docker compose up -d
  args:
    chdir: "{{ APP_DIR }}/prometheus"
